#!/usr/bin/env python3
"""
AIOS Host-Evidence Lock
======================

LLM is allowed to *analyse* host evidence but is NEVER allowed to
invent / restate / recompute any system fact that authoritative
host evidence already pins.  This module extracts a stable set of
*anchor facts* — concrete (kind, value) pairs with a short
immutable ``HF-NNN`` identifier — and exposes three helpers:

* :func:`extract_anchor_facts` — walk host-evidence items and pull
  out every concrete numeric / state anchor.
* :func:`render_verified_facts_block` — produce the program-generated
  ``## Verified Facts`` block that is appended to the deliverable
  (the LLM cannot mutate it).
* :func:`filter_fact_conflicts` — scan the LLM output and REPLACE any
  material fact line that conflicts with an anchor with a brief
  marker (the conflict is logged on the workflow hash for audit).

Only the well-defined fact classes listed in :data:`HF_FACT_REGEXES`
are checked.  Analysis, recommendations and risk prose are NOT
filtered.
"""
from __future__ import annotations

import re
from typing import Any, Dict, List, Tuple


HF_PROMPT_INSTRUCTION = (
    "\n\nAUTHORITATIVE FACTS are immutable. Each anchor fact is pinned "
    "by an HF-* id. You MUST reference facts by id (e.g. "
    "'[HF-001]') and MUST NOT invent, replace, recompute, paraphrase "
    "or restate any value for: PID, listening port count, service "
    "ActiveState, restart count, HTTP status, version, commit hash, "
    "timestamp, or any other concrete numeric / state field covered "
    "by an HF-* anchor. Your job is analysis, recommendations, and "
    "risk discussion based on those immutable facts. The Verified "
    "Facts block at the end of the output is generated by AIOS, not "
    "by you; do not try to rewrite it."
)


HF_FACT_REGEXES = (
    ("main_pid", re.compile(r"\bMain\s*PID[:\u3000]\s*(\d+)")),
    ("pid", re.compile(r"\bPID[:\u3000]\s*(\d+)")),
    ("tasks", re.compile(r"\bTasks[:\u3000]\s*(\d+)(?!\d)")),
    ("memory_mb", re.compile(r"\bMemory[:\u3000]\s*(\d+(?:\.\d+)?)\s*M\b")),
    ("cpu", re.compile(r"\bCPU[:\u3000]\s*(\d+(?:\.\d+)?)\s*ms\b")),
    ("listening_count", re.compile(r"\blistening[_\s-]?count[:\u3000=]\s*(\d+)")),
    ("match_count", re.compile(r"\bmatch[_\s-]?count[:\u3000=]\s*(\d+)")),
    ("http_status", re.compile(r"\bstatus[:\u3000=]\s*(\d{3})\b")),
    ("active_state", re.compile(
        r"\bActiveState[:\u3000=]\s*(active|inactive|failed|activating|deactivating)\b"
    )),
    ("active", re.compile(
        r"\bActive[:\u3000]\s*(active\s*\(running\))"
    )),
    ("failed_unit", re.compile(
        r"((?:[\w.-]+\.service))\s+loaded\s+failed\s+failed"
    )),
    ("timestamp", re.compile(
        r"\b(20\d{2}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+\-]\d{2}:?\d{2})?)\b"
    )),
)


def extract_anchor_facts(evidence):
    """Walk the host-evidence items and pull out concrete anchors."""
    anchors = []
    if not evidence:
        return anchors
    items = list(evidence.get("items") or [])
    for item in items:
        if not isinstance(item, dict):
            continue
        cap = str(item.get("capability") or "")
        body = str(item.get("body") or "")
        unit = str(item.get("unit") or "")
        path = str(item.get("path") or "")
        url = str(item.get("url") or "")
        haystack = "\n".join(s for s in (body, unit, path, url) if s)
        for kind, regex in HF_FACT_REGEXES:
            for m in regex.finditer(haystack):
                anchors.append({
                    "kind": kind,
                    "value": m.group(1),
                    "capability": cap,
                    "span": m.group(0),
                })
    if len(anchors) > 256:
        anchors = anchors[:256]
    for i, a in enumerate(anchors, start=1):
        a["id"] = f"HF-{i:03d}"
    return anchors


def render_verified_facts_block(anchors):
    """Render the program-generated ``## Verified Facts`` block.

    The LLM cannot influence this content — it is a pure function
    of the host-evidence body.  Each line is ``[HF-NNN] kind=value``
    so the LLM can reference facts by id and so the post-filter can
    cross-check the LLM's prose.
    """
    if not anchors:
        return ""
    lines = ["## Verified Facts (program-generated; immutable)"]
    for a in anchors:
        kind = str(a.get("kind", ""))
        value = str(a.get("value", ""))
        fid = str(a.get("id", ""))
        cap = str(a.get("capability", ""))
        if cap:
            lines.append(f"[{fid}] {kind}={value}  # from {cap}")
        else:
            lines.append(f"[{fid}] {kind}={value}")
    return "\n".join(lines)


_FACT_CONFLICT_LINE = re.compile(
    r"(?P<kind>Main\s*PID|PID|Tasks|Memory|CPU|listening[_\s-]?count|"
    r"match[_\s-]?count|status|ActiveState|Active|active|loaded|"
    r"failed_unit|failed.unit)\b"
    r"[^:=\n]*[:\u3000=]\s*(?P<value>\d+(?:\.\d+)?|\S+)"
)

# Catch Chinese / English prose that claims "no failures" /
# "无失败" / "no failed unit" etc.  These are direct contradictions
# of the SYSTEMD_USER_FAILED anchor (which always names a concrete
# unit when present).
_NO_FAILURE_PROSE_PATTERNS = (
    re.compile(r"无\s*(?:失败|异常|fail|error)"),
    re.compile(r"没有\s*(?:任何)?\s*(?:失败|异常|fail|error)"),
    re.compile(r"不\s*(?:包含|存在)\s*(?:任何)?\s*(?:失败|fail)"),
    re.compile(r"no\s+failed\s+unit", re.IGNORECASE),
    re.compile(r"\bno\s+failure\b", re.IGNORECASE),
    re.compile(r"\b(?:no|without)\s+(?:any|known)\s+(?:fail|error)", re.IGNORECASE),
)


def _is_failed_unit_in_anchors(anchors):
    return any(a.get("kind") == "failed_unit" for a in anchors)


def _normalise_kind(kind):
    kind = kind.replace(" ", "").replace("\u00a0", "").lower()
    if "mainpid" in kind or "main_pid" in kind:
        return "main_pid"
    if "active" in kind and "state" in kind:
        return "active_state"
    if "active" in kind:
        return "active"
    if "listening" in kind or "listeningcount" in kind:
        return "listening_count"
    if "match" in kind:
        return "match_count"
    if kind in ("tasks", "task"):
        return "tasks"
    if "memory" in kind:
        return "memory_mb"
    if "cpu" in kind:
        return "cpu"
    if "status" in kind or kind == "httpstatus":
        return "http_status"
    if "activestate" in kind:
        return "active_state"
    return ""


def _values_equal(expected, got):
    """Loose numeric / state equality.

    ``Main PID: 82472`` and ``Main PID 82472`` and ``82472`` should
    all match an anchor with value ``82472``.  We compare on the
    canonical numeric form when both sides parse as numbers.
    """
    e, g = str(expected).strip(), str(got).strip()
    if e == g:
        return True
    try:
        return float(e) == float(g)
    except (TypeError, ValueError):
        return False


def filter_fact_conflicts(deliverable, anchors):
    """Remove (do NOT replace) any material fact line in the LLM
    deliverable that conflicts with an authoritative anchor.

    Returns ``(cleaned_text, conflicts)`` where ``conflicts`` is a
    list of dicts with keys ``id`` / ``kind`` / ``expected`` /
    ``conflicting_line`` / ``line_no``.  Conflicting lines are
    DELETED outright — never replaced with a marker — because the
    Reviewer (hermes) treats any string that looks like a fabricated
    filter-marker as an additional unsupported claim and rejects the
    deliverable.  Deletion is the only behaviour that simultaneously
    protects the LLM's analysis prose and the canonical evidence.
    """
    if not deliverable or not anchors:
        return deliverable, []
    by_kind = {}
    for a in anchors:
        by_kind.setdefault(str(a.get("kind", "")), []).append(a)
    has_failed_unit = _is_failed_unit_in_anchors(anchors)
    conflicts = []
    lines = deliverable.splitlines()
    keep_lines = []
    for idx, line in enumerate(lines, start=1):
        m = _FACT_CONFLICT_LINE.search(line)
        prose_hit = None
        if has_failed_unit and not m:
            for prose_re in _NO_FAILURE_PROSE_PATTERNS:
                if prose_re.search(line):
                    prose_hit = "no_failure_prose"
                    break
        if not m and prose_hit is None:
            keep_lines.append(line)
            continue
        if m:
            kind = str(m.group("kind")).strip().lower()
            value = str(m.group("value")).strip().rstrip(".,;)")
            norm = _normalise_kind(kind)
            if not norm:
                keep_lines.append(line)
                continue
            candidates = by_kind.get(norm, [])
            match = None
            for cand in candidates:
                if _values_equal(cand.get("value", ""), value):
                    match = cand
                    break
            if match is not None:
                keep_lines.append(line)
                continue
            if candidates:
                anchor = candidates[0]
                anchor_id = str(anchor.get("id", ""))
                anchor_value = str(anchor.get("value", ""))
            else:
                anchor_id = ""
                anchor_value = "(no anchor)"
            conflicts.append({
                "id": anchor_id,
                "kind": norm,
                "expected": anchor_value,
                "conflicting_line": line,
                "line_no": idx,
            })
        else:
            # prose contradiction: deliverable claims "no failures"
            # but a ``failed_unit`` anchor exists in evidence.
            failed_anchor = next(
                (a for a in anchors if a.get("kind") == "failed_unit"),
                None,
            )
            anchor_id = str((failed_anchor or {}).get("id", ""))
            anchor_value = str((failed_anchor or {}).get("value", ""))
            conflicts.append({
                "id": anchor_id,
                "kind": "failed_unit",
                "expected": anchor_value,
                "conflicting_line": line,
                "line_no": idx,
            })
    cleaned = "\n".join(keep_lines)
    return cleaned, conflicts


__all__ = [
    "HF_PROMPT_INSTRUCTION",
    "HF_FACT_REGEXES",
    "extract_anchor_facts",
    "render_verified_facts_block",
    "filter_fact_conflicts",
]
